// src/models/enemyPilot.ts

import { Pilot } from './player';
import { Book } from '../services/book';
import { selectManeuvers } from './maneuvers';

export class EnemyPilot extends Pilot {
  private book: Book;

  private static goDirections: string[] = [
    "Go direction",
    "left",
    "straight",
    "right",
    "right",
    "right",
    "left",
    "left",
    "right",
    "right",
    "right",
    "left",
    "right",
    "right",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "straight",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "left",
    "right",
    "right",
    "left",
    "left",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "righ",
    "left",
    "left",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "left",
    "left",
    "straight",
    "right",
    "right",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "straight",
    "straight",
    "right",
    "right",
    "left",
    "straight",
    "straight",
    "right",
    "right",
    "right",
    "right",
    "straight",
    "straight",
    "right",
    "right",
    "right",
    "right",
    "straight",
    "straight",
    "straight",
    "left",
    "straight",
    "straight",
    "left",
    "left",
    "left",
    "left",
    "straight",
    "straight",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "right",
    "left",
    "left",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "left",
    "straight",
    "left",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "left",
    "right",
    "right",
    "left",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "straight",
  ];

  constructor(book: Book) {
    super();
    this.book = book;
  }

  getNextManeuver(_page: number, _otherMove: string): string {
    const pred1 = (details: any) => !details.difficult;
    const goDirection = EnemyPilot.goDirections[_page];
    const pred2 = (details: any) => pred1(details) && details.direction === goDirection;
    const tail = this.book.lookupBool("Tail", _page);
    let pred3 = pred2;
    if (tail) {
      let speed: string | null = null;
      const range = this.book.lookup("Range", _page);
      if (range === "Short") speed = "cruise";
      if (range === "Medium") speed = "fast";
      if (range === "Long") speed = "fast";
      if (speed !== null) {
        pred3 = (details: any) => pred2(details) && details.speed === speed;
      }
    }
    const options = selectManeuvers(pred3);
    if (options.length === 0) return "Straight";
    const index = Math.floor(Math.random() * options.length);
    return options[index];
  }

  getDamage(range: number): number {
    return range;
  }
}