// src/models/enemyAce.ts

import { Pilot } from './player';
import { getManeuverDetails } from './maneuvers';

export class EnemyAce extends Pilot {
  private static maneuvers: Map<number, string[]> = new Map([
    [1, [
      "left:Left_then_cruise",
      "left:Stall_left",
      "left:Stall_right",
      "left:Cruise_then_left",
      "straight:Weave_right_left",
      "straight:Slip_left",
      "straight:Cruise_then_left",
      "straight:Stall_left",
      "right:Stall",
      "right:Slip_left",
      "right:Straight",
    ]],
    [2, [
      "left:Slip_left",
      "right:Slip_right",
      "straight:Straight"
    ]],
    [3, [
      "right:Right_then_cruise",
      "right:Stall_right",
      "right:Wing_right",
      "right:Cruise_then_right",
      "straight:Weave_left_right",
      "straight:Slip_right",
      "straight:Cruise_then_right",
      "straight:Stall_right",
      "left:Stall",
      "left:Slip_left",
      "left:Straight"
    ]],
    [4, ["Rotary_turn", "Immlemann", "Turn_right", "Wing_right"]],
    [5, ["Rotary_turn", "Immlemann"]],
    [6, ["Turn_left"]],
    [7, ["Stall_left"]],
    [8, [
      "left:Slip_right",
      "right:Cruise_then_right",
      "straight:Cruise_then_right"
    ]],
    [9, ["Stall_right"]],
    [10, ["Rotary_turn", "Turn_right", "Barrel_roll_right", "Fast", "Fast_then_right"]],
    [11, ["Fast_then_right", "Rotary_turn", "Turn_right", "Immlemann"]],
    [12, ["Turn_left", "Immlemann", "Right_then_fast", "Wing_left"]],
    [13, ["Weave_left_right", "Stall_right", "Straight", "Fast"]],
    [14, ["Turn_right", "Rotary_turn", "Stall_right", "Wing_right"]],
    [15, ["Stall", "Stall_right", "Slip_right"]],
    [16, ["Immlemann", "Stall", "Fast_then_right", "Slip_right", "Slip_left", "Barrel_roll_right", "Barrel_roll_left", "Rotary_turn", "Wing_left", "Wing_right"]],
    [17, ["Stall", "Stall_left", "Slip_left"]],
    [18, ["Wing_left", "Stall_left", "Turn_left", "Barrel_roll_left", "Fast_then_left"]],
    [19, ["Stall_left", "Left_then_cruise", "Turn_left", "Fast_then_left", "Left_then_fast"]],
    [20, ["Fast_then_right", "Fast_then_left", "Immlemann", "Rotary_turn", "Wing_right", "Wing_left"]],
    [21, ["Stall_right", "Slip_right", "Fast_then_right", "Right_then_fast", "Right_then_cruise"]],
    [22, ["Stall_right", "Turn_right", "Rotary_turn", "Wing_right"]],
    [23, ["Fast_then_left", "Left_then_fast", "Immlemann", "Barrel_roll_left", "Wing_left"]],
    [24, ["Turn_left", "Wing_left", "Barrel_roll_left", "Fast_then_left", "Left_then_fast", "Fast"]],
    [25, ["Turn_left", "Wing_left", "Stall_left", "Left_then_cruise", "Cruise_then_left", "Fast_then_left", "Left_then_fast"]],
    [26, ["Stall_left", "Turn_left", "Wing_left", "Cruise_then_left", "Slip_left", "Stall"]],
    [27, ["Fast", "Fast_then_right", "Barrel_roll_right", "Rotary_turn", "Immlemann", "Right_then_fast", "Wing_right", "Slip_right"]],
    [28, ["Straight"]],
    [29, ["Straight"]],
    [30, ["Straight"]],
    [31, ["Straight"]],
    [32, ["Straight"]],
    [33, ["Straight"]],
    [34, ["Straight"]],
    [35, ["Straight"]],
    [36, ["Straight"]],
    [37, ["Straight"]],
    [38, ["Straight"]],
    [39, ["Straight"]],
    [40, ["Straight"]],
    [41, ["Straight"]],
    [42, ["Straight"]],
    [43, ["Straight"]],
    [44, ["Straight"]],
    [45, ["Straight"]],
    [46, ["Straight"]],
    [47, ["Straight"]],
    [48, ["Straight"]],
    [49, ["Straight"]],
    [50, ["Straight"]],
    [51, ["Straight"]],
    [52, ["Straight"]],
    [53, ["Straight"]],
    [54, ["Straight"]],
    [55, ["Straight"]],
    [56, ["Straight"]],
    [57, ["Straight"]],
    [58, ["Straight"]],
    [59, ["Straight"]],
    [60, ["Straight"]],
    [61, ["Straight"]],
    [62, ["Straight"]],
    [63, ["Straight"]],
    [64, ["Straight"]],
    [65, ["Straight"]],
    [66, ["Straight"]],
    [67, ["Straight"]],
    [68, ["Straight"]],
    [69, ["Straight"]],
    [70, ["Straight"]],
    [71, ["Straight"]],
    [72, ["Straight"]],
    [73, ["Straight"]],
    [74, ["Straight"]],
    [75, ["Straight"]],
    [76, ["Straight"]],
    [77, ["Straight"]],
    [78, ["Straight"]],
    [79, ["Straight"]],
    [80, ["Straight"]],
    [81, ["Straight"]],
    [82, ["Straight"]],
    [83, ["Straight"]],
    [84, ["Straight"]],
    [85, ["Straight"]],
    [86, ["Straight"]],
    [87, ["Straight"]],
    [88, ["Straight"]],
    [89, ["Straight"]],
    [90, ["Straight"]],
    [91, ["Straight"]],
    [92, ["Straight"]],
    [93, ["Straight"]],
    [94, ["Straight"]],
    [95, ["Straight"]],
    [96, ["Straight"]],
    [97, ["Straight"]],
    [98, ["Straight"]],
    [99, ["Straight"]],
    [100, ["Straight"]],
    [101, ["Straight"]],
    [102, ["Straight"]],
    [103, ["Straight"]],
    [104, ["Straight"]],
    [105, ["Straight"]],
    [106, ["Straight"]],
    [107, ["Straight"]],
    [108, ["Straight"]],
    [109, ["Straight"]],
    [110, ["Straight"]],
    [111, ["Straight"]],
    [112, ["Straight"]],
    [113, ["Straight"]],
    [114, ["Straight"]],
    [115, ["Straight"]],
    [116, ["Straight"]],
    [117, ["Straight"]],
    [118, ["Straight"]],
    [119, ["Straight"]],
    [120, ["Straight"]],
    [121, ["Straight"]],
    [122, ["Straight"]],
    [123, ["Straight"]],
    [124, ["Straight"]],
    [125, ["Straight"]],
    [126, ["Straight"]],
    [127, ["Straight"]],
    [128, ["Straight"]],
    [129, ["Straight"]],
    [130, ["Straight"]],
    [131, ["Straight"]],
    [132, ["Straight"]],
    [133, ["Straight"]],
    [134, ["Straight"]],
    [135, ["Straight"]],
    [136, ["Straight"]],
    [137, ["Straight"]],
    [138, ["Straight"]],
    [139, ["Straight"]],
    [140, ["Straight"]],
    [141, ["Straight"]],
    [142, ["Straight"]],
    [143, ["Straight"]],
    [144, ["Straight"]],
    [145, ["Straight"]],
    [146, ["Straight"]],
    [147, ["Straight"]],
    [148, ["Straight"]],
    [149, ["Straight"]],
    [150, ["Straight"]],
    [151, ["Straight"]],
    [152, ["Straight"]],
    [153, ["Straight"]],
    [154, ["Straight"]],
    [155, ["Straight"]],
    [156, ["Straight"]],
    [157, ["Straight"]],
    [158, ["Straight"]],
    [159, ["Straight"]],
    [160, ["Straight"]],
    [161, ["Straight"]],
    [162, ["Straight"]],
    [163, ["Straight"]],
    [164, ["Straight"]],
    [165, ["Straight"]],
    [166, ["Straight"]],
    [167, ["Straight"]],
    [168, ["Straight"]],
    [169, ["Straight"]],
    [170, ["Straight"]],
    [171, ["Straight"]],
    [172, ["Straight"]],
    [173, ["Straight"]],
    [174, ["Straight"]],
    [175, ["Straight"]],
    [176, ["Straight"]],
    [177, ["Straight"]],
    [178, ["Straight"]],
    [179, ["Straight"]],
    [180, ["Straight"]],
    [181, ["Straight"]],
    [182, ["Straight"]],
    [183, ["Straight"]],
    [184, ["Straight"]],
    [185, ["Straight"]],
    [186, ["Straight"]],
    [187, ["Straight"]],
    [188, ["Straight"]],
    [189, ["Straight"]],
    [190, ["Straight"]],
    [191, ["Straight"]],
    [192, ["Straight"]],
    [193, ["Straight"]],
    [194, ["Straight"]],
    [195, ["Straight"]],
    [196, ["Straight"]],
    [197, ["Straight"]],
    [198, ["Straight"]],
    [199, ["Straight"]],
    [200, ["Straight"]],
    [201, ["Straight"]],
    [202, ["Straight"]],
    [203, ["Straight"]],
    [204, ["Straight"]],
    [205, ["Straight"]],
    [206, ["Straight"]],
    [207, ["Straight"]],
    [208, ["Straight"]],
    [209, ["Straight"]],
    [210, ["Straight"]],
    [211, ["Straight"]],
    [212, ["Straight"]],
    [213, ["Straight"]],
    [214, ["Straight"]],
    [215, ["Straight"]],
    [216, ["Straight"]],
    [217, ["Straight"]],
    [218, ["Straight"]],
    [219, ["Straight"]],
    [220, ["Straight"]],
    [221, ["Straight"]],
    [222, ["Straight"]],
    [223, ["Straight"]],
  ]);

  getNextManeuver(_page: number, _playerManeuver: string): string {
    return this.chooseOption(EnemyAce.maneuvers.get(_page) || [], _playerManeuver);
  }

  getDamage(range: number): number {
    return range;
  }

  private chooseOption(options: string[], playerManeuver: string): string {
    let playerDirection: string | null = null;
    const details = getManeuverDetails(playerManeuver);
    if (details) {
      playerDirection = details.direction;
    }
    return this.chooseOptionFiltered(this.getOptions(options, playerDirection));
  }

  private chooseOptionFiltered(options: string[]): string {
    if (!options || options.length === 0) return "Straight";
    const index = Math.floor(Math.random() * options.length);
    return options[index];
  }

  private getOptions(options: string[], direction: string | null): string[] {
    const result: string[] = [];
    for (const option of options) {
      if (option.includes(":")) {
        const fields = option.split(":");
        if (fields.length === 2) {
          if (direction === null || fields[0] === direction) {
            result.push(fields[1]);
          }
        }
      } else {
        result.push(option);
      }
    }
    return result;
  }
}